kokkos版ベンチマーク
Qulacs-Osaka/qulacs2023_benchmark pull request #14
Opened 2023-08-22 08:22 UTC by gandalfr-KY

各ゲートは2重ループで実装してあります。
qg2で動作確認済です。
1重ループ版やkeichi先生がswapを用いて実装したものはとりあえずexperimental.hppに置いてます。

2023-08-31 02:38 UTC, KowerKoint commented on benchmarks/kokkos/main.cpp
> +        if(control_list(i, 0) == control_list(i, 1)) control_list(i, 1) = n_qubits - 1;
```suggestion
        if(control_list(i, 0) == control_list(i, 1)) {
            if(n_qubits - 1 == targets(i, 0)) control_lists(i, 1) = n_qubits - 2;
            else control_list(i, 1) = n_qubits - 1;
        }
```
すみません　元のやつが間違ってました

2023-09-07 07:22 UTC, KowerKoint approved these changes

2023-09-12 05:44 UTC, ikanago requested changes

2023-09-12 05:44 UTC, ikanago commented on benchmarks/kokkos/main.cpp
> +            if(n_qubits - 1 == targets(i, 0)) control_lists(i, 1) = n_qubits - 2;
`control_lists` が未定義でビルドできなかったので確認お願いします！
```suggestion
            if(n_qubits - 1 == targets(i, 0)) control_list(i, 1) = n_qubits - 2;
```

2023-09-14 06:23 UTC, gandalfr-KY commented on benchmarks/kokkos/main.cpp
> +            if(n_qubits - 1 == targets(i, 0)) control_lists(i, 1) = n_qubits - 2;
修正しました！すみません！

2023-09-14 07:16 UTC, merged